services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ebay_restapi_app
    restart: unless-stopped
    working_dir: /var/www/laravel
    volumes:
      - ./laravel:/var/www/laravel
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - ebay_restapi_network

  web:
    image: nginx:latest
    container_name: ebay_restapi_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./laravel:/var/www/laravel
      - ./tecdoc:/var/www/tecdoc
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - python-app
      - tecdoc
    networks:
      - ebay_restapi_network

  db:
    image: supabase/postgres:15.1.0.117
    container_name: ebay_restapi_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ebay_restapi_network

  meta:
    image: ghcr.io/supabase/postgres-meta:v0.75.0
    container_name: ebay_restapi_meta
    environment:
      PG_META_PORT: 8080
      PG_META_DB_HOST: db
      PG_META_DB_NAME: postgres
      PG_META_DB_USER: postgres
      PG_META_DB_PASSWORD: secret
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - ebay_restapi_network

  studio:
    image: supabase/studio:latest
    container_name: ebay_restapi_studio
    restart: unless-stopped
    environment:
      STUDIO_PG_META_URL: http://meta:8080
      SUPABASE_URL: http://localhost:8000
      SUPABASE_REST_URL: http://localhost:8000/rest/v1/
      SUPABASE_ANON_KEY: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwiaWF0IjoxNjQxNzY5MjAwLCJleHAiOjE3OTk1MzU2MDAsInJvbGUiOiJhbm9uIn0.dc_X5iR_VP_qT0zsiyj_I_OZ2T9FtRU2BBNWN8Bu4GE
      SUPABASE_SERVICE_KEY: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwiaWF0IjoxNjQxNzY5MjAwLCJleHAiOjE3OTk1MzU2MDAsInJvbGUiOiJzZXJ2aWNlX3JvbGUifQ.M2i_7qxC8YW_YHQb_O_TH_TsnqE9UvwC_A7nfeIwJ7U
    ports:
      - "3000:3000"
    depends_on:
      - db
      - meta
    networks:
      - ebay_restapi_network

  python-app:
      image: python:3.9
      container_name: ebay_restapi_python
      working_dir: /python
      volumes:
          - ./python:/python
          - ./.env:/.env
      expose:
        - "8000"
      command: sh -c "cp /.env /python/.env 2>/dev/null && pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
      depends_on:
          - db
      networks:
          - ebay_restapi_network
  tecdoc:
    build:
      context: .
      dockerfile: DockerfileTecdoc
    container_name: ebay_restapi_tecdoc
    restart: unless-stopped
    working_dir: /var/www/tecdoc
    volumes:
      - ./tecdoc:/var/www/tecdoc
    env_file:
      - .env
    expose:
      - "9000"
    networks:
      - ebay_restapi_network

volumes:
  postgres_data:

networks:
  ebay_restapi_network:
    driver: bridge
