services:
  app:
    build: ./laravel
    container_name: ebay_restapi_app
    restart: unless-stopped
    working_dir: /var/www/laravel
    volumes:
      - ./laravel:/var/www/laravel
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - ebay_restapi_network

  laravel-worker:
    container_name: ebay_restapi_laravel_worker
    build: ./laravel
    working_dir: /var/www/laravel
    volumes:
      - ./laravel:/var/www/laravel
    command: php artisan queue:work --sleep=3 --tries=3 --timeout=30000
    env_file:
      - .env
    depends_on:
      - app
      - db
    networks:
      - ebay_restapi_network

  web:
    image: nginx:latest
    container_name: ebay_restapi_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./laravel:/var/www/laravel
      - ./tecdoc:/var/www/tecdoc
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - python-app
      - tecdoc
      - log-service
    networks:
      - ebay_restapi_network

  db:
    image: supabase/postgres:15.1.0.117
    container_name: ebay_restapi_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ebay_restapi_network

  meta:
    image: ghcr.io/supabase/postgres-meta:v0.75.0
    container_name: ebay_restapi_meta
    environment:
      PG_META_PORT: 8080
      PG_META_DB_HOST: db
      PG_META_DB_NAME: postgres
      PG_META_DB_USER: postgres
      PG_META_DB_PASSWORD: secret
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - ebay_restapi_network

  studio:
    image: supabase/studio:latest
    container_name: ebay_restapi_studio
    restart: unless-stopped
    environment:
      STUDIO_PG_META_URL: http://meta:8080
      SUPABASE_URL: http://localhost:8000
      SUPABASE_REST_URL: http://localhost:8000/rest/v1/
      SUPABASE_ANON_KEY: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwiaWF0IjoxNjQxNzY5MjAwLCJleHAiOjE3OTk1MzU2MDAsInJvbGUiOiJhbm9uIn0.dc_X5iR_VP_qT0zsiyj_I_OZ2T9FtRU2BBNWN8Bu4GE
      SUPABASE_SERVICE_KEY: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwiaWF0IjoxNjQxNzY5MjAwLCJleHAiOjE3OTk1MzU2MDAsInJvbGUiOiJzZXJ2aWNlX3JvbGUifQ.M2i_7qxC8YW_YHQb_O_TH_TsnqE9UvwC_A7nfeIwJ7U
    ports:
      - "3000:3000"
    depends_on:
      - db
      - meta
    networks:
      - ebay_restapi_network

  python-app:
    build: ./python
    container_name: ebay_restapi_python
    working_dir: /python
    volumes:
        - ./python:/python
    env_file:
      - .env
    expose:
      - "8000"
    depends_on:
        - db
    networks:
        - ebay_restapi_network

  tecdoc:
    build: ./tecdoc
    container_name: ebay_restapi_tecdoc
    restart: unless-stopped
    working_dir: /var/www/tecdoc
    volumes:
      - ./tecdoc:/var/www/tecdoc
    env_file:
      - .env
    expose:
      - "9000"
    networks:
      - ebay_restapi_network

  log-service:
    build: ./log-service
    container_name: ebay_restapi_log
    volumes:
      - ./log-service:/log-service
    working_dir: /log-service
    env_file:
      - .env
    expose:
      - "8000"
    networks:
      - ebay_restapi_network

volumes:
  postgres_data:

networks:
  ebay_restapi_network:
    driver: bridge
